### ISSUE TITLE
node-firefox-reload-css error: Cannot find module 'es6-Promise'

### ISSUE THREAD

**Issue by kiddhustle** [mozilla/node-firefox-examples-gulp#1]
Unfortunately I see the following error when I run the following command:
     npm start

This appears to be due to a problem with the es6-promise module being referenced in the node-firefox-reload-css module.
## System:

OS: Ubuntu 14.04
Hardware: Lenovo g50
## Error message:

Error: Cannot find module 'es6-Promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/boss/workspace/node-firefox-examples-gulp/node_modules/node-firefox-reload-css/index.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! node-firefox-examples-gulp@1.0.0 start: `gulp build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-firefox-examples-gulp@1.0.0 start script.
npm ERR! This is most likely a problem with the node-firefox-examples-gulp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-firefox-examples-gulp
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/boss/workspace/node-firefox-examples-gulp
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/boss/workspace/node-firefox-examples-gulp/npm-debug.log
npm ERR! not ok code 0
boss@boss-Lenovo-G50-70:~/workspace/node-firefox-examples-gulp$ ^C
boss@boss-Lenovo-G50-70:~/workspace/node-firefox-examples-gulp$ npm owner
npm ERR! Usage: 
npm ERR! npm owner add <username> <pkg>
npm ERR! npm owner rm <username> <pkg>
npm ERR! npm owner ls <pkg>
npm ERR! not ok code 0

**Comment by tofumatt** [comment]
Ah, this is because we uppercased the module name in the require call when we shouldn't have. We fixed this in most modules but missed it here.  I'm on my phone so I can't push to npm right now, but I'll fix this and push the fix once I get home. Thanks for filing the issue!

**Comment by tofumatt** [comment]
Ah, this should have been filed over at https://github.com/mozilla/node-firefox-reload-css

Filed: https://github.com/mozilla/node-firefox-reload-css/issues/3, will fix ASAP.

**Comment by kiddhustle** [comment]
OK cool thanks
